// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Dt0eO8I5xjgzT-3hWpYg5JkSnyxpQRw',
    appId: '1:953006189226:web:d1bca5e6a9bcf85de37ed3',
    messagingSenderId: '953006189226',
    projectId: 'pingmyride-82279',
    authDomain: 'pingmyride-82279.firebaseapp.com',
    storageBucket: 'pingmyride-82279.firebasestorage.app',
    measurementId: 'G-68B2G57G7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB7RPbrvuuUMScGmMgI_L8CGTIuNPt-H8',
    appId: '1:953006189226:android:f69b2b04b017be5ce37ed3',
    messagingSenderId: '953006189226',
    projectId: 'pingmyride-82279',
    storageBucket: 'pingmyride-82279.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpUAovfnrc_vj6x-cSh5_6FCcyiMLprQA',
    appId: '1:953006189226:ios:b30d6f40051842cbe37ed3',
    messagingSenderId: '953006189226',
    projectId: 'pingmyride-82279',
    storageBucket: 'pingmyride-82279.firebasestorage.app',
    iosBundleId: 'com.chandra.pingmyride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpUAovfnrc_vj6x-cSh5_6FCcyiMLprQA',
    appId: '1:953006189226:ios:b30d6f40051842cbe37ed3',
    messagingSenderId: '953006189226',
    projectId: 'pingmyride-82279',
    storageBucket: 'pingmyride-82279.firebasestorage.app',
    iosBundleId: 'com.chandra.pingmyride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2Dt0eO8I5xjgzT-3hWpYg5JkSnyxpQRw',
    appId: '1:953006189226:web:713a6b2ba91375eee37ed3',
    messagingSenderId: '953006189226',
    projectId: 'pingmyride-82279',
    authDomain: 'pingmyride-82279.firebaseapp.com',
    storageBucket: 'pingmyride-82279.firebasestorage.app',
    measurementId: 'G-3QT5J05X0V',
  );
}
